### ISSUE TITLE
Using brew to build on OSX Big Sur fails

### ISSUE THREAD

**Issue by ravenboy** [avrdudes/avrdude#1012]
your directions say to use

brew install cmake hidapi libftdi1 libusb libelf

this command fails:

Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
Warning: No available formula with the name "libftdi1". Did you mean libftdi or libftdi0?
==> Searching for similarly named formulae...
These similarly named formulae were found:
libftdi                                  libftdi0 ✔
To install one of them, run (for example):
  brew install libftdi
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
raventalking@Johns-MacBook-Pro ~ %

**Comment by mcuee** [comment]
You are right, you should install libftdi instead.
https://github.com/avrdudes/avrdude/wiki/Building-AVRDUDE-for-macOS --> need to be updated for Homebrew

Ref:
https://formulae.brew.sh/formula/libftdi
https://formulae.brew.sh/formula/libftdi0 (this will work as well but not recommended).

**Comment by mcuee** [comment]
@MCUdude or @mariusgreuel 
Please help to fix the Wiki. Thanks.

**Comment by MCUdude** [comment]
@mcuee just change the brew command in the wiki to:

```
brew install cmake hidapi libftdi libusb libelf
```

Right?

**Comment by mcuee** [comment]
Yes that is correct.

**Comment by ravenboy** [comment]
thanks much

**Comment by ravenboy** [comment]
thanks much

**Comment by MCUdude** [comment]
Wiki updated!
