### ISSUE TITLE
Missing COPYING file in avrdude-7.0.tar.gz

### ISSUE THREAD

**Issue by ffontaine** [avrdudes/avrdude#1014]
Official tarball ([avrdude-7.0.tar.gz](https://github.com/avrdudes/avrdude/releases/download/v7.0/avrdude-7.0.tar.gz)) doesn't contain COPYING file.

**Comment by dl8dtl** [comment]
Well, the preferred build system is CMake now.
I've only rolled the tarballs in the historic archive layout for those people who might urgently need it that way, and they do not pretend being complete in any way.

**Comment by ffontaine** [comment]
OK, I'll switch to cmake when bumping avrdude in buildroot.
