### ISSUE TITLE
Unknown option '-s' on command line

### ISSUE THREAD

**Issue by acolomb** [avrdudes/avrdude#1032]
The so-called "safe mode" feature was removed in #859 and with it the option parsing for the `-s` flag.  That causes problems with scripts calling avrdude after upgrading to version 7.0.  A well-behaved command line program should accept, but ignore, deprecated options instead of choking on them.

**Comment by MCUdude** [comment]
See issue #890.
A fix for -s should probably be submitted as well.

**Comment by mcuee** [comment]
> See issue #890. A fix for -s should probably be submitted as well.

Yes I agree that a fix like #890 is also good for this case.
