### ISSUE TITLE
SerialUPDI does not support page erase 

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1111]
Now that #1106 is merged, page erase support is getting more relevant, as Avrdude only needs to erase the pages modified and not the whole memory. @dbuchwald did a fantastic job with the current SerialUPDI implementation but is lacking (flash) page erase support.

https://github.com/avrdudes/avrdude/blob/44fe5bec2dd2f016d135f0d2f02173045d7aeef5/src/serialupdi.c#L885-L891

However, it appears that the underlying functionality is already present:
https://github.com/avrdudes/avrdude/blob/44fe5bec2dd2f016d135f0d2f02173045d7aeef5/src/updi_nvm.c#L1075-L1088 

I'm [currently working](https://github.com/mcudude/avrdude/tree/jtag3-page-erase-updi) on UPDI page erase support for JTAG3 compatible programmers.

**Comment by dbuchwald** [comment]
Hey,

Sorry to have not responded before, I’m in a middle of life-induced shitstorm, but I will try to make some time to look into it.

I’m honestly not sure why I haven’t made link between the standard page erase function of AVRDUDE and the serialupdi implementation ported over from the Microchip python programmer, but it should be feasible.

Would it be possible for you guys to provide me with some examples of AVRDUDE invocation where page erase is performed using other UPDI programmers (like the JTAG3 for instance) and short description of the expected output? This will make it much easier for me to investigate further.

Please note: the main limitation of certain features is how the NVM programmer on UPDI chips works; chances are it will not be very efficient or will require fallback to byte erase mode. I had similar issue with the USERROW (if I recall correctly), that I wanted to file a bug against Microchip, but it sort of never happened.

Anyway, I will do my best as soon as I can.

Best regards,
Dawid

On 6 Oct 2022, at 08:24, Hans ***@***.******@***.***>> wrote:



Now that #1106<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favrdudes%2Favrdude%2Fpull%2F1106&data=05%7C01%7C%7Ce67a6312f4b44971ab5508daa76361dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006342533797062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WR5QYSJkGDA%2BJ%2FDfoDKZ6NsEiCEuUFRZdRUEKWlxbaI%3D&reserved=0> is merged, page erase support is getting more relevant, as Avrdude only needs to erase the pages modified and not the whole memory. @dbuchwald<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbuchwald&data=05%7C01%7C%7Ce67a6312f4b44971ab5508daa76361dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006342533953293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NBISQouaj%2BLZ0Aw6w2217s67Cqe4IwsG%2Bhu7yy7u6CE%3D&reserved=0> did a fantastic job with the current SerialUPDI implementation but is lacking (flash) page erase support.

https://github.com/avrdudes/avrdude/blob/44fe5bec2dd2f016d135f0d2f02173045d7aeef5/src/serialupdi.c#L885-L891<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favrdudes%2Favrdude%2Fblob%2F44fe5bec2dd2f016d135f0d2f02173045d7aeef5%2Fsrc%2Fserialupdi.c%23L885-L891&data=05%7C01%7C%7Ce67a6312f4b44971ab5508daa76361dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006342533953293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1H3liaKh3JhgR7LrF3QO5tnbWJRyOpJMP7r3T231CNE%3D&reserved=0>

However, it appears that the underlying functionality is already present:
https://github.com/avrdudes/avrdude/blob/44fe5bec2dd2f016d135f0d2f02173045d7aeef5/src/updi_nvm.c#L1075-L1088<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favrdudes%2Favrdude%2Fblob%2F44fe5bec2dd2f016d135f0d2f02173045d7aeef5%2Fsrc%2Fupdi_nvm.c%23L1075-L1088&data=05%7C01%7C%7Ce67a6312f4b44971ab5508daa76361dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006342533953293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DAARwGuBygnq6IthxABfkvIK%2Fvs7JgoG%2BPjPcKZ2PcA%3D&reserved=0>

I'm currently working<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcudude%2Favrdude%2Ftree%2Fjtag3-page-erase-updi&data=05%7C01%7C%7Ce67a6312f4b44971ab5508daa76361dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006342533953293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZAhG%2FZg1p31ycnmePxfBSUhZiOX0LLOYHnKRWvfdbHc%3D&reserved=0> on UPDI page erase support for JTAG3 compatible programmers.

**Comment by MCUdude** [comment]
Hi Dawid!

> Sorry to have not responded before, I’m in a middle of life-induced shitstorm, but I will try to make some time to look into it.

I'm sorry to hear that! There's no rush, so do it if/when you have the energy to look into it.

Here are some test commands you can use for testing with the latest upstream version of Avrdude. You can paste it all at once in the terminal window. For more info regarding terminal flash write, see #1106.

```
echo erase | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'read flash 0x3100 16' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'write flash 0x3100 "hello, world\n"' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'read flash 0x3100 16' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'write flash 0x3100 "Hello, world\n"' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'read flash 0x3100 16' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'write flash 0x3100 "hello, world\n"' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
echo 'read flash 0x3100 16' | ./avrdude -qqp atmega3209 -c pkobn_updi -t
```

Here's the result with and without page erase support for a JTAG3 programmer. Notice the warning message and the read time for the second last command:

<details>
<summary> Without jtag3 UPDI page erase fix </summary>

```
$ echo erase | ./avrdude -p avr128db48 -c pkobn_updi -t 

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> erase 
avrdude: erasing chip

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... done

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |hello, world ...|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "Hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "Hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... done

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  48 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |Hello, world ...|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... avrdude: jtag3_page_erase: not an Xmega device

Reading | ################################################## | 100% 21.94s
Erasing | ################################################## | 100% 0.02s
Writing | ################################################## | 100% 0.24s

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |hello, world ...|


avrdude done.  Thank you.
```
</details>

<details>
<summary> With jtag3 UPDI page erase fix </summary>

```
echo erase | ./avrdude -p avr128db48 -c pkobn_updi -t 

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> erase 
avrdude: erasing chip

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... done

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |hello, world ...|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "Hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "Hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... done

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  48 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |Hello, world ...|


avrdude done.  Thank you.

$ echo 'write flash 0x1000 "hello, world\n"' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> write flash 0x1000 "hello, world\n" 

Writing | ################################################## | 100% 0.09s

avrdude: writing cache to device... done

avrdude done.  Thank you.

$ echo 'read flash 0x1000 16' | ./avrdude -p avr128db48 -c pkobn_updi -t

         Vtarget                      : 3.31 V
         PDI/UPDI clock Xmega/megaAVR : 100 kHz

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e970c (probably avr128db48)
>>> read flash 0x1000 16 

Reading | ################################################## | 100% 0.09s

1000  68 65 6c 6c 6f 2c 20 77  6f 72 6c 64 0a 00 ff ff  |hello, world ...|


avrdude done.  Thank you.
```
</details>

**Comment by stefanrueger** [comment]
@dbuchwald Thanks for reply - I hope things go well.


In order to force page_erase() one can stay in the avrdude terminal (now there is the new `flush` command):
```
erase
write flash 0 0
flush
write flash 0 255
flush
```

Or, from a linux bash
```
$ echo "erase;write flash 0 0;flush;write flash 0 255;flush" | tr \; \\n | avrdude -c ... -qqp ... -t
avrdude> erase
avrdude: erasing chip
avrdude> write flash 0 0
avrdude> flush
avrdude: synching cache to device... done
avrdude> write flash 0 255
avrdude> flush
avrdude: synching cache to device... reading/chip erase/writing cycle needed ... done
```

The reading/chip erase/writing cycle is not necessary when  page_erase is properly implemented. The terminal tries to use page_erase() whenever it needs to set a previously cleared bit in flash; if it's not there or doesn't work the chip is read, erased and written back.

**Comment by dbuchwald** [comment]
Hey,

First of all, sorry for the whole delay, it’s just that I couldn’t find time to properly test it until now.

I have filed new PR for this change, it seems to be working fine, but…

There is something weird about the data being written to and from the cache. Maybe it’s that I don’t understand what is supposed to happen, but I was confused enough to put all the info in the PR.

Let me know if the PR provides the functionality you expected.

Best regards,
Dawid Buchwald

On 6 Oct 2022, at 20:22, Stefan Rueger ***@***.******@***.***>> wrote:



@dbuchwald<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbuchwald&data=05%7C01%7C%7C3411ec515d2446ac3e0e08daa7c7bc0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006773539447802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J89DXom5ekPebiI8SXKeAwkQH9vJKkxLQTWCp58nnvM%3D&reserved=0> Thanks for reply - I hope things go well.

In order to force page_erase() one can stay in the avrdude terminal (now there is the new flush command):

erase
write flash 0 0
flush
write flash 0 255
flush


Or, from a linux bash

$ echo "erase;write flash 0 0;flush;write flash 0 255;flush" | tr \; \\n | avrdude -c ... -qqp ... -t
avrdude> erase
avrdude: erasing chip
avrdude> write flash 0 0
avrdude> flush
avrdude: synching cache to device... done
avrdude> write flash 0 255
avrdude> flush
avrdude: synching cache to device... reading/chip erase/writing cycle needed ... done


The reading/chip erase/writing cycle is not necessary when page_erase is properly implemented. The terminal tries to use page_erase() whenever it needs to set a previously cleared bit in flash; if it's not there or doesn't work the chip is read, erased and written back.

**Comment by stefanrueger** [comment]
> avrdude> write flash 0 255

255 is interpreted as signed integer. Either use 0xff or 255U to make it unsigned. A signed 255 does not fit into one signed byte that has a range of [-128, 127]. This needs two bytes.

**Comment by mcuee** [comment]
PR #1151 has been merged.
* #1151
