### ISSUE TITLE
Overhaul string checking and handling (Low Priority)

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1127]
I'm just leaving this as a reminder that this is something we should look into when the list of open PRs has been reduced.

Ideally, we should create a separate file (str.c/h?) where all string handling functions are located.

The problem is that we're using different functions to do the same thing, and the code may look a bit messy in some places.

#### Here are a few examples from jtagmkii.c where both `strncmp` and `strcmp` is used.

https://github.com/avrdudes/avrdude/blob/e14e5d2f7488b87d3d3f8308521bac6d2ea5d263/src/jtagmkII.c#L679-L682

https://github.com/avrdudes/avrdude/blob/e14e5d2f7488b87d3d3f8308521bac6d2ea5d263/src/jtagmkII.c#L961-L962

#### In jtag3.c, `matches` are used extensively. However, the name "matches" is very misleading, as it only checks if a string *starts with* another string. In the example below, `matches` will catch all valid fuse* names (fuse0 ... fuse8).

https://github.com/avrdudes/avrdude/blob/e14e5d2f7488b87d3d3f8308521bac6d2ea5d263/src/jtag3.c#L1985-L1988

IMO the code would be easier to read and maintain if we had the following functions instead

* `str_eq(str, pattern)`, str is equal to pattern
* `str_starts(str, pattern)`, str starts with pattern
* `str_ends(str, pattern)`, str ends with pattern
* `str_contains(str, pattern)`, str contains pattern

**Comment by mcuee** [comment]
Yes this is a good idea to streamline the codes for easier maintainence.

**Comment by stefanrueger** [comment]
Great idea to have a systematic and mnemonic(!) set of string comparison function for AVRDUDE.

... and given the example with the fuses, I wonder it it is a good idea to also have a function `avr_mem_is_fuse_type()`, which could also include the aliases `osccfg` etc. This in analogy to the existing `avr_is_flash_type()`, which currently runs `strcmp()` against 4 known flash-type memories.

Independent of this, to figure out whether something is a fuse-like memory one could also extend the table `avr_mem_order` to include pairs of memory name and memory type (eeprom, flash, fuse, signature, ram (`data`), ...) to save string compares against a list of possible names at run-time. `avr_mem_order` came into life to give all memories in the part description in `avrdude.conf` a definitive order, but it could double up to inform about memory type, too.

**Comment by MCUdude** [comment]
The string functions needed are quite simple:

```c
bool str_starts(const char *str, const char *starts) {
  return strncmp(str, starts, strlen(starts)) == 0;
}


bool str_eq(const char *str1, const char *str2) {
  return strncmp(str1, str2, strlen(str1)) == 0;
}


bool str_contains(const char *str, const char *substr) {
  return !!strstr(str, substr);
}


bool str_ends(const char *str, const char *ends) {
  int str_len  = strlen(str);
  int ends_len = strlen(ends);
  
  if (ends_len > str_len)
    return 0;
  
  for (size_t i = 0; i < ends_len; i++) {
    if (str[str_len - i] != ends[ends_len - i])
      return 0;
  }
  
  return 1;
}
```

But since @stefanrueger have proven himself to be a highly skilled "find and replace wizard", it might be better if you submitted the PR with the new string checking functions?

> ... and given the example with the fuses, I wonder it it is a good idea to also have a function avr_mem_is_fuse_type(), which could also include the aliases osccfg etc.

This is a very good idea! And when looking at the existing code, there are several places where `avr_mem_is_flash_type` and `avr_mem_is_eeprom_type` can be used instead of the typical string checking using `strcmp`.

**Comment by MCUdude** [comment]
@stefanrueger is this something you have time to look into?
My "find and replace" skills are no where as good as yours, and the way you elegantly replaced thousands of `avrdude_message` lines with `msg_` with practically no error was very impressive.

**Comment by stefanrueger** [comment]
@MCUdude From experience an undertaking like this is very time consuming. Even if search/replacement is done automatically, it still costs time to set up and there is still a lengthy review to be had. The wrapper functions need attention to detail and style too (the suggested implementation of `str_eq()` above is wrong, eg). Whilst I still think this is would be nice, it's not something that I have on the list of things that I prioritise for the time being.

BTW, I like your work where you express programmer capabilities explicitly in the `extra_features` component in `avrdude.conf`, which will lead to removing a fair number of strcmp() against the programmer name. This is very welcome as the name of a programmer should be irrelevant for its working.

I'd suggest to close this issue and just open a PR when someone comes round to submitting that.

**Comment by MCUdude** [comment]
I suggest we keep the issue open as a reminder that this is something we'd like to do sometime, but it not prioritized as it's just "house keeping"

**Comment by MCUdude** [comment]
@stefanrueger you mentioned in #1320 that you'll replace all `strtol` functions in the Avrdude codebase with a function that handles `errno` properly. Would it make sense to add this to str.c/str.h along with the other string-checking functions mention in one of the previous posts here?

Even though the entire code base doesn't get updated to use `str_eq/starts/ends/contains`, it would be neat to be able to use this on new functionality such as adding `-xhelp` to all programmers that support extended parameters. [The approach I started working on](https://github.com/avrdudes/avrdude/issues/1287#issuecomment-1490989011) uses lots of string checking, and these functions would increase code readability and reduce verbosity.

**Comment by stefanrueger** [comment]
> `avr_str2num()` function (generic conversion will be able to handle binary etc)

That is actually near the top of the things I wanted to implement pretty soon (Easter would be particularly germane); not sure what the best place is for this; `term.c` b/c it probably would be based on the existing code in `term.c` that does a through job on converting diverse data (would extend this to binary); or `config.c` b/c of the central role this function would play in the grammar/lexer.

I'd be keen to see the use of strcmp() et al reduced first before tackling this current issue: you did a great job with the `extra_features` component in avrdude.conf, which will lead to removing a fair number of `strcmp()` against the programmer name; I am poised to suggest a [similar thing for the memory type](https://github.com/avrdudes/avrdude/issues/1330#issuecomment-1487579845) probably sometime between Easter and Whitsun. Both have already and will further reduce strcmp() use.

BTW, I'm not against starting `str.c` and populating with a few carefully named and *carefully implemented* string comparison functions, though it would have to be someone other than me who runs that show.
