### ISSUE TITLE
Inconsistent terminal output routes re stdout and stderr

### ISSUE THREAD

**Issue by stefanrueger** [avrdudes/avrdude#1130]
The parms command in the terminal has always used the normal AVRDUDE messaging system, printing to stderr, and now follows the `-qq` reduction of what is printed. This means that the `parms` command can print nothing in the terminal:
```
$ echo parms | avrdude -p m328p -qqc arduino -t -P /dev/ttyUSB0
avrdude> parms
```

I think the terminal parms command should write to stdout (just like the other commands), and not follow the gradual reduction that `-qq` effects on the `msg_level()` system. 

Trouble is that the library functions avr_display() and programmer_display() share the functions that the terminal `parms` command uses where we *want*  gradual reduction with `-qq`. 

In order to solve this discrepancy, we'd need to change the API for pgm->print_parm() to add a FILE * parameter that can be stdout or stderr.

<s>Errors that happen in the terminal go partially to stdout (if the error is within the terminal parsing, eg) but errors of called library functions go to stderr. This is inconsistent. I suggest errors always go to stderr and normal (expected) terminal output goes to stdout.</s> [edit - was already consistent, all errors go to stderr in terminal]

Thoughts?

**Comment by stefanrueger** [comment]
I suggest the following solution:
  - Review use of terminal_message() in term.c and make the errors/warnings use the new msg_level() system
  - Change the API of pgm->print_parm() to have an additional FILE * argument
  - Extend the current msg_level() macros to pass on stdout/stderr, the line number and file name of the source
  - Change terminal_message(MSG_INFO, ...) to a macro term_info(...) that utilises the updated messaging system with stdout

**Comment by stefanrueger** [comment]
See PR #1132

**Comment by mcuee** [comment]
Ref: PR #1132 should fix this. Unfortunately pulling in readline is a bit complicated under macOS and MSYS2 mingw.
https://github.com/avrdudes/avrdude/pull/1132#issuecomment-1285260358
