### ISSUE TITLE
MSYS2: Linker error when readline is present.

### ISSUE THREAD

**Issue by mariusgreuel** [avrdudes/avrdude#1293]
On MSYS2/MinGW64, it appears that libreadline is linked against ncurses. Currently, main does not link correctly.

```console
[100%] Linking C executable avrdude.exe
D:/Work/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Work/msys64/mingw64/lib/libreadline.a(display.o):(.text+0xed0): undefined reference to `tputs'
D:/Work/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Work/msys64/mingw64/lib/libreadline.a(display.o):(.text+0xf39): undefined reference to `tputs'
...
```

**Comment by mcuee** [comment]
Previous discussions:
* https://github.com/avrdudes/avrdude/issues/1155
Previous PR to fix this issue:
* https://github.com/avrdudes/avrdude/pull/1270

Ultimate long term solution:
* https://github.com/avrdudes/avrdude/issues/1271

**Comment by mcuee** [comment]
PR #1294 is good and it fixes the issue.
