### ISSUE TITLE
-c urclock should progressively shrink metadata with increasing application sizes

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1352]
I stumbled across this when integrating Urboot into [MicroCore](https://github.com/MCUdude/MicroCore).
In this case, The ATtiny13 has 1024 bytes of flash storage, and the bootloader occupies 256 bytes, which means that there are 768 bytes left for the user program. However, the default Urclock behaviour is to make sure there is room for all metadata. If not, it won't upload the user program even though there technically is room for it.

I think it would be useful with a new extra parameter that will store metadata only _if_ there is room for it. 

```
$ ./avrdude -pattiny13a -curclock -P/dev/cu.usbserial-1410 -b57600 -Uflash:w:/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_37307/Flash_iterate.ino.hex:i
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9007 (probably t13a)
avrdude: Note: flash memory has been specified, an erase cycle will be performed.
         To disable this feature, specify the -D option.
avrdude: erasing chip
         delaying chip erase until first -U upload to flash
avrdude: reading input file /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_37307/Flash_iterate.ino.hex for flash
         with 766 bytes in 1 section within [0, 0x2fd]
         using 24 pages and 2 pad bytes
avrdude error: input [0x0000, 0x02fd] overlaps metadata [0x02fb, 0x02ff], consider -xnometadata

avrdude done.  Thank you.


$ ./avrdude -pattiny13a -curclock -P/dev/cu.usbserial-1410 -b57600 -Uflash:w:/var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_37307/Flash_iterate.ino.hex:i -xnometadata
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9007 (probably t13a)
avrdude: Note: flash memory has been specified, an erase cycle will be performed.
         To disable this feature, specify the -D option.
avrdude: erasing chip
         delaying chip erase until first -U upload to flash
avrdude: reading input file /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_37307/Flash_iterate.ino.hex for flash
         with 766 bytes in 1 section within [0, 0x2fd]
         using 24 pages and 2 pad bytes
avrdude: preparing flash input for device bootloader
avrdude: writing 766 bytes flash ...
Writing | ################################################## | 100% 0.45 s 
avrdude: 766 bytes of flash written
avrdude: verifying flash memory against /var/folders/6l/ypg6qbw172v1s4vtt6g990tw0000gn/T/arduino_build_37307/Flash_iterate.ino.hex
Reading | ################################################## | 100% 0.23 s 
avrdude: 766 bytes of flash verified

avrdude done.  Thank you.
```

**Comment by stefanrueger** [comment]
> a bit [of] the bootloader space [as] the "metadata present" flag

Not possible on a number of levels: Metadata are provided by the Avrdude `-c urclock` programmer and are independent of the bootloader (they are actually available with optiboot, too), so Avrdude wouldn't know where to find an unused bit in it; also the bootloader would need to overwrite itself (it's the bootloader that writes flash here); in theory, metadata could be implemented at avrdude level independent of programmers, though the flash store metadata may only be of limited use (unless the part finds a way to modify flash w/o a bootloader).

> So what is the least amount of metadata that will be stored if no -x flag is specified? 

Currently? It's 11+n bytes, with n in [2, 254] being the length of the file name incl nul. That can be reduced to 11, 5, or *zero* bytes with use of -x options. (Actually, the 11/5 can be 15/9 when the part has a large flash >64k as the flash store metadata needs larger addresses.) The second suggestion above, and the one you seem to prefer, would progressively shrink that to *one* (not zero) depending on size of uploaded sketch.

The subtle difference between zero and one bytes has its roots in that it's unwise to automatically, silently switch from running a metadata regime to no metadata.
