### ISSUE TITLE
Avrdude creates srec files in an unnecessarily lax way

### ISSUE THREAD

**Issue by stefanrueger** [avrdudes/avrdude#1391]
AVRDUDE takes a relatively liberal interpretation of the Motorola S-Record format when reading them (good) but also when creating them (less good): header and count records are not created, the record types S1/2/3 are freely mixed within a file and always closed off with S9 (but S8 should close S2 and A7 should close off S3). Here a small example:

```
$ avrdude -qq -p m328p -c dryrun -A -U flash:r:out.srec:s
$ srec_cat out.srec -output out.raw -binary
srec_cat: out.srec: 1: warning: no header record
```

I suggest creating S-Record files that follow a stricter format, eg, the one in [wikipedia](https://en.wikipedia.org/wiki/SREC_(file_format)), and thus will be usable by more programs.

**Comment by mcuee** [comment]
Indeed there is an issue and PR #1392 fixed the issue.

```
$ ./avrdude_git -qq -p m2560 -c dryrun -A -U flash:r:out.srec:s

$ srec_cat out.srec -output out.raw -binary
srec_cat: out.srec: 1: warning: no header record

$ ./avrdude_pr1392 -qq -p m2560 -c dryrun -A -U flash:r:out.srec:s

$ srec_cat out.srec -output out.raw -binary
(no more warning messages)
```
