### ISSUE TITLE
Request for adding AVRDUDE to Windows Package Manager (Winget)

### ISSUE THREAD

**Issue by hayschan** [avrdudes/avrdude#1447]
Hello AVRDUDE team,

I would like to request the addition of AVRDUDE to the Windows Package Manager (Winget). As a Linux user, I have enjoyed the convenience of being able to install AVRDUDE with a single command using the package manager (e.g. `sudo apt-get install avrdude`). However, I have noticed that Windows users currently do not have this option, and instead must manually download and install AVRDUDE, which can be inconvenient and time-consuming.

AVRDUDE is a widely used utility for programming AVR microcontrollers, and it is available on many platforms including Windows. By making AVRDUDE available through Winget, Windows users would be able to install and update AVRDUDE with a simple command `winget install avrdude`, and benefit from the convenience and reliability of a package manager.

I believe that adding AVRDUDE to Winget would greatly improve the user experience for Windows users who rely on this utility for their projects. It would also help to promote the use of AVRDUDE among Windows users, and encourage more people to use AVR microcontrollers for their projects.

Thank you for your consideration, and please let me know if there is anything I can do to support this request.

Best regards,
Hays Chan

**Comment by mcuee** [comment]
You can request through winget?
