### ISSUE TITLE
Avrdude online documentation doesn't point to the latest user manual

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1481]
When browsing https://avrdudes.github.io/avrdude/ I realized that when I click on "Current" (HTML or PDF) I'm not actually reading the manual for the latest release, but rather the manual for 7.1. Maybe @dl8dtl can have a look at this? Thanks!

**Comment by dl8dtl** [comment]
Since it seems that was never updated at all, I don't think the idea of a "current" documentation makes much sense, unless we integrate it somehow into CI. Thus, I just removed that.

**Comment by mcuee** [comment]
@dl8dtl 

I agree with you here.

On the other hand, current Linux x86_64 github action does build the document.
