### ISSUE TITLE
Support AT32UC3L series

### ISSUE THREAD

**Issue by IvoBCD** [avrdudes/avrdude#1484]
Not having much luck using avrdude to program an AT32UC3L064 devboard:

```
$ avrdude -C +avrdude-at32uc3l.conf -p uc3l064 -c pickit4  -U flash:r:readback.bin
avrdude warning: part definition for AT32UC3L064 lacks ocdrev; guessing 3
avrdude error: JTAGEN fuse disabled?
avrdude error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower the bit clock frequency, e.g. -B 125kHz
:
```

Using this config file:
```
part
    desc                   = "AT32UC3L064";
    id                     = "uc3l064";
    prog_modes             = PM_AVR32JTAG | PM_aWire;
    signature              = 0xed 0xc0 0x3f;

    memory "flash"
        paged              = yes;
        size               = 0x10000;
        page_size          = 512;           # bytes
        num_pages          = 128;
        offset             = 0x80000000;
        readsize           = 512;           # bytes
    ;
;
```

and pin mapping:

PICkit4:

- PICkit4 pin#2: AVR JTAG VTG   4: UC3 VCC  
- PICkit4 pin#3: AVR JTAG GND   2: UC3 GND       
- PICkit4 pin#4: AVR JTAG TDO   3: UC3 TDO     
- PICkit4 pin#5: AVR JTAG TCK   1: UC3 TCK      
- PICkit4 pin#6: AVR JTAG RESET 6: UC3 RESET   
- PICkit4 pin#7: AVR JTAG TDI   9: UC3 TDI    
- PICkit4 pin#8: AVR JTAG TMS   5: UC3 TMS 

Should this work, or does avrdude need more than a config file to support this target ?

**Comment by MCUdude** [comment]
AFAIK, PICkit4 doesn't support AVR32s. @stefanrueger I thought Avrdude was supposed to print an error message telling the user that the selected programmer doesn't support the particular part?

**Comment by stefanrueger** [comment]
> supposed to print an error message telling the user that the selected programmer doesn't support the particular part

AVRDUDE does not do that but could.  Programmer modes and part modes were introduced to enable a user to figure out which programmers should be able to program a part, in principle:
```
$ avrdude -p at32uc3a0512 -c\?

Valid programmers for part AT32UC3A0512 are:
  atmelice           = Atmel-ICE (ARM/AVR) via AVR32JTAG
  atmelice_jtag      = Atmel-ICE (ARM/AVR) via AVR32JTAG
  dragon_jtag        = Atmel AVR Dragon via AVR32JTAG
  jtag2fast          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2              = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2slow          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag3              = Atmel AVR JTAGICE3 via AVR32JTAG
  jtagmkII           = Atmel JTAG ICE mkII via AVR32JTAG
  jtagmkII_avr32     = Atmel JTAG ICE mkII via aWire
  jtag2avr32         = Atmel JTAG ICE mkII via aWire
  powerdebugger      = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG
  powerdebugger_jtag = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG
  xplainedpro        = Atmel AVR XplainedPro via AVR32JTAG
```

**Comment by MCUdude** [comment]
> AVRDUDE does not do that but could

Got it. However, having Avrdude tell you that this programmer does not support this part, even before trying to communicate with the programmer would be a nice addition I think.

**Comment by mcuee** [comment]
BTW, we can say AVR32 parts are in general not supported, only one part AVR32UC3A0512 is listed as supported.

**Comment by mcuee** [comment]
@stefanrueger 

BTW, I think even the following may not be true.
```
$ avrdude -p at32uc3a0512 -c\?

Valid programmers for part AT32UC3A0512 are:
  atmelice           = Atmel-ICE (ARM/AVR) via AVR32JTAG
  atmelice_jtag      = Atmel-ICE (ARM/AVR) via AVR32JTAG
  dragon_jtag        = Atmel AVR Dragon via AVR32JTAG
  jtag2fast          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2              = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2slow          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag3              = Atmel AVR JTAGICE3 via AVR32JTAG
  jtagmkII           = Atmel JTAG ICE mkII via AVR32JTAG
  jtagmkII_avr32     = Atmel JTAG ICE mkII via aWire
  jtag2avr32         = Atmel JTAG ICE mkII via aWire
  powerdebugger      = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG
  powerdebugger_jtag = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG
  xplainedpro        = Atmel AVR XplainedPro via AVR32JTAG
```

Reference:
* https://github.com/avrdudes/avrdude/discussions/1435
* https://github.com/avrdudes/avrdude/discussions/1434

**Comment by mcuee** [comment]
@dl8dtl and @MCUdude 

Just wondering if you know which programmer really supports the single AVR32 chip? Or shall we even drop that support and declare that AVR32 chips are not supported.

**Comment by MCUdude** [comment]
I wouldn't mind if we removed AVR32 support. I doubt many are using this feature since nobody complains about the lack of support for other AVR32 chips.

**Comment by stefanrueger** [comment]
There is some code for aWire and JTAGAVR32 programming interfaces. I always thought people would just copy the singe AT32UC3L series part that AVRDUDE supports and modify for the different memory sizes as @IvoBCD seems to have done. I wouldn't mind to keep that support and add the parts that work with that, so would be happy to entertain a PR by someone who uses these parts (assuming the current code base does a good job).

**Comment by mcuee** [comment]
> I wouldn't mind to keep that support and add the parts that work with that, so would be happy to entertain a PR by someone who uses these parts (assuming the current code base does a good job).

I am okay with this.

**Comment by mcuee** [comment]
Closing this issue for now. 

@IvoBCD 
You can reopen this issue if you are willing to submit a PR to add the support for more AVR32 chips (as well as programmers).

**Comment by mcuee** [comment]
@stefanrueger 

BTW, from the following two references, we need to remove some existing programmers from the list of supported programmer for AVR32.
* https://github.com/avrdudes/avrdude/discussions/1435
* https://github.com/avrdudes/avrdude/discussions/1434

```
$ avrdude -p at32uc3a0512 -c\?

Valid programmers for part AT32UC3A0512 are:
  atmelice           = Atmel-ICE (ARM/AVR) via AVR32JTAG (need to remove)
  atmelice_jtag      = Atmel-ICE (ARM/AVR) via AVR32JTAG  (need to remove)
  dragon_jtag        = Atmel AVR Dragon via AVR32JTAG  (need to remove)
  jtag2fast          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2              = Atmel JTAG ICE mkII via AVR32JTAG
  jtag2slow          = Atmel JTAG ICE mkII via AVR32JTAG
  jtag3              = Atmel AVR JTAGICE3 via AVR32JTAG 
  jtagmkII           = Atmel JTAG ICE mkII via AVR32JTAG
  jtagmkII_avr32     = Atmel JTAG ICE mkII via aWire
  jtag2avr32         = Atmel JTAG ICE mkII via aWire
  powerdebugger      = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG  (need to remove)
  powerdebugger_jtag = Atmel PowerDebugger (ARM/AVR) via AVR32JTAG  (need to remove)
  xplainedpro        = Atmel AVR XplainedPro via AVR32JTAG  (need to remove ???)
```
