### ISSUE TITLE
Add support for AVR-EB

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1489]
Apparently, Microchip has released a pack that supports the AVR16EB14, AVR16EB20, AVR16EB28, and AVR16EB32.
Adding them to Avrdude is trivial, but @stefanrueger will have to update avrintel.c/h.

https://packs.download.microchip.com/#collapse-Microchip-AVR-Ex-DFP-pdsc

**Comment by stefanrueger** [comment]
| Adding them to Avrdude is trivial

Nothing ever is. There are two new memories to consider here: 
 - `bootrow`, which seems to be of the `userrow` type and might require a terminal cache
 - New fuse `pdicfg` which is *two* bytes at offset 10, ie outside the convention of `fuse0` ... `fuse9`

Both requires careful review of the current code base, in particular the two-byte fuse with one config parameter that crosses a byte boundary (that will be the reason for the two-byte fuse).

> avrintel.c/.h

This is mostly automatic, though.

Does anyone have this part or, failing that, a data sheet? In absence of either I'd assume `bootrow` to be like `usersig` when implementing the terminal cache for it, ie, that `bootrow` a paged additional memory that is not erased on chip erase.
