### ISSUE TITLE
Can you integrate debugWIRE protocol into avrdude?

### ISSUE THREAD

**Issue by wanggaoteng** [avrdudes/avrdude#1492]
Hi, many avrs support debugWIRE for debugging, such as atmega328p. The debugWIRE protocol has been carefully investigated and documented by [RikusW](http://www.ruemohr.org/docs/debugwire.html ), and it has been implemented by [dcbrown](https://github.com/dcwbrown/dwire-debug) at a very low cost. 
But the debugWIRE has one disadvantage: it can not change the fuse of avr. In fact, the avrdude can do this, but it can not debug (means the real hardware debug).
In this way, a new demand arises: Can you integrate debugWIRE protocol into avrdude? Make the avrdude can debug the common avrs which support the debugWIRE protocol.
Best regards.

**Comment by mcuee** [comment]
avrdude is for programming and it does support debugWire protocol with some Microchip/Atmel tools.

You want debugging, so this request is not valid as avrdude will not support debugging. Please checkout the other project.
https://github.com/avrdudes/avarice
