### ISSUE TITLE
avrdude.conf not latest even after purge and reinstall

### ISSUE THREAD

**Issue by andreikovari** [avrdudes/avrdude#1501]
Current setup: Laptop with Ubuntu, custom Atmega1608 connected to an Atmel ICE programmer via UPDI

While trying to flash an Atmega1608, I've got the following error
![image](https://github.com/avrdudes/avrdude/assets/53494213/784a1043-f613-4b42-99ff-d108d46411af)
It seems that the target mcu is not found in avrdude.conf file. Tried uninstalling and reinstalling avrdude.
When I checked the version of the avrdude, I got this link:
![image](https://github.com/avrdudes/avrdude/assets/53494213/76b48754-7e7a-4647-adf0-204ea4dba7a2)
http://savannah.nongnu.org/projects/avrdude/

The installation was done with these commands: 
sudo apt-get update
sudo apt-get install avrdude

Not a linux guru, but it seems that the path for the source of avrdude is not set properly (?)
Any feedback is greatly appreciated!

**Comment by mcuee** [comment]
You may have to ask Ubuntu for this issue as this is not an avrdude issue but rather Ubuntu packaging issue. They are still using a very old avrdude version (6.3).

You may want to totally delete the binaries from Ubuntu and then build from source. Latest release is 7.2.
https://github.com/avrdudes/avrdude/releases/tag/v7.2

You can also try to use my binary if you do not want to build from source.
https://github.com/mcuee/avrdude/releases/tag/v7.2
