### ISSUE TITLE
[bug #26312] OS X Intel AVR-Dragon "jtagmkII_getsync(): sign-on command: status -1" error

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#152]
fertigtm <None>
Thu 23 Apr 2009 04:33:27 PM UTC

Hello folks,

I have had problems with avrdude and an avrdragon on my Intel Mac. Im running Mac OS X 10.4.11. So far the problem was that avrdude says:
avrdude: usbdev_open(): Found AVRDRAGON, serno: XXXXX
avrdude: jtagmkII_getsync(): sign-on command: status -1
avrdude: jtagmkII_getsync(): sign-on command: status -1

Searching the net I found entries to a similar problem but without a solution to fix it. It seems that at least one person could bring it up and running with upgrading to OS X 10.5.

As I'm not willing to upgrade yet I tracked to problem down. For this I tried out several version of libusb. All had the same behavior, they failed.

At least I could avoid the error by removing stk500v2_drain(pgm, 0) call in stk500v2_dragon_isp_open().

It seems that the first initial read to USB which is done by the stk500v2_drain function let the corresponding Mac OS X function return with a timeout. This results in an error which let the application exit.

With a small patch you can avoid this behavior. For me it works great. I tested it with uploading a program and downloading the fuse bytes.

The attached file contains a patch against avrdude 5.5.

[file #18002: osxintelDragonFix.diff](https://savannah.nongnu.org/bugs/download.php?file_id=18002)

This issue was migrated from https://savannah.nongnu.org/bugs/?26312

**Comment by MCUdude** [comment]
I'm closing this issue because it's almost 13 years old, with a MacOS version not currently supported by pretty much anyone.
I have no issues getting my AVR Dragon to work with my mac.
