### ISSUE TITLE
Add "Sanguino" Optiboot hashes to urclock.c

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1532]
See https://github.com/MCUdude/MightyCore/issues/285 for details

It turns out that some 3D printer boards have the really old [Sanguino Optiboot bootloader](https://github.com/Lauszus/Sanguino/tree/master/bootloaders/optiboot) installed, and this won't work with `-c urclock` unless the boot size is manually specified using `-xbootsize`.
https://github.com/Lauszus/Sanguino/tree/master/bootloaders/optiboot

IIRC we can calculate the hashes for these files so that `-c urclock` can recognize the bootloader, and the bootsize doesn't have to be manually specified.

**Comment by stefanrueger** [comment]
> IIRC we can calculate the hashes for these files

There is a [bash script](https://github.com/avrdudes/avrdude/blob/main/tools/bootloader-hash) for this in this repo.
