### ISSUE TITLE
avrdude7.2 unable to detect atmelice - works with avrdude6.3

### ISSUE THREAD

**Issue by feroze-mohamed** [avrdudes/avrdude#1579]
I have been using avrdude6.3 on windows 10 and 11 without issues.

But lately we needed support for ATTINY1626, so upgraded to v7.2

While 6.3 works (detects atmelice) , v7.2 says unable to detect the atmelice

used ZADIG to change the driver to libusb

v7.2 : 
![image](https://github.com/avrdudes/avrdude/assets/137377525/c22b49d1-6f77-413f-b62d-e60687a7d117)

v6.3:
<img width="546" alt="image" src="https://github.com/avrdudes/avrdude/assets/137377525/b5fad46f-5bf6-4fd5-844d-e1551cbde6a4">

**Comment by MCUdude** [comment]
Using Zadig, can you try to change your driver to WinUSB and see if this helps?

**Comment by MCUdude** [comment]
OK. You may have to use the original driver. I think it's called hidusb.
You can't use Zadig to select this, but you can do it under the Windows Device Manager.
On the bright size, this is the same driver as Atmel Studio uses, so one doesn't need to switch between drivers anymore.

**Comment by MCUdude** [comment]
I don't use Windows on a regular basis, so I don't really know. @mcuee would have to chime in.

**Comment by mcuee** [comment]
@feroze-mohamed 

Please try my MinGW build to see if it works.
https://github.com/mcuee/avrdude/releases/tag/v7.2

For example:
[avrdude-v7.2_mingw64.zip](https://github.com/mcuee/avrdude/releases/download/v7.2/avrdude-v7.2_mingw64.zip)

If the above build works (using libusb-1.0+libusb-compat-0.1) and the offcial Windows binary (using avrdude-libusb) does not work, it could be that you hit the existing bug.
https://github.com/avrdudes/avrdude/issues/968

**Comment by stefanrueger** [comment]
> Basically both systesm work with mingw version with different drivers.
>
> Thank you for your support

Thanks for reporting back @feroze-mohamed Does this mean the issue can be closed?
