### ISSUE TITLE
Provide a simple way to perform a chip factory reset

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1619]
It would be really neat if terminal mode could support some sort of factory reset option, so that `factory` or `reset` could reset the fuses to the default value and erase the EEPROM and flash memory. And if the bitclock is set too high, make sure that it's reduced to atleast 1/4 of the internal clock speed

**Comment by stefanrueger** [comment]
The first part is doable within the confines of what the -c programmer can do, but how would the project attempt

> And if the bitclock is set too high, make sure that it's reduced to atleast 1/4 of the internal clock speed

That is, how would AVRDUDE know what the internal clock speed of a factory-reset part is? AVRDUDE knows ca 350 parts.

**Comment by stefanrueger** [comment]
And for the time being the following would work (insert the intended real programmer for *programmer*):

`avrdude -cdryrun -qq -pATmega328P -Tc | avrdude -c`*programmer* -pATmega328P -t -T erase`

And, obviously, use the correct part name, too (twice).

Caveat: there are some parts for which AVRDUDE has no factory reset values for fuses.

**Comment by stefanrueger** [comment]
Turns out the hard part is not to figure out what the initial clock speed is after factory resetting fuse values and carrying out an MCU reset, but to figure out whether a programmer can set its bit rate, and how to do this. Instead the `factory reset` command prints the new F_CPU after MCU reset.
