### ISSUE TITLE
USE_STATIC_LIBS builds fail to detect libreadline.so

### ISSUE THREAD

**Issue by ndim** [avrdudes/avrdude#1624]
When building avrdude with `-D USE_STATIC_LIBS:BOOL=YES`, cmake fails to detect the installed `libreadline.so` file and prints `DON'T HAVE  libreadline`.

This appears to be due to an oversight which happend when adapting `CMakeLists.txt` for detecting `libreadline` in the static case (commit 0ea4b08b2), which has since been copied over to the new-in-7.3 `libserialport` detection (commit 0be6568b7).

https://github.com/avrdudes/avrdude/blob/a336e47a6e1fe069c45096edaeda1b4841ad7ce5/CMakeLists.txt#L120-L140

The fix appears to be to follow the same pattern which is already used in all the other library checks and add `foo` after `libfoo.a`:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 73bb0714..bde9304b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -124,8 +124,8 @@ if(USE_STATIC_LIBS)
     set(PREFERRED_LIBHIDAPI libhidapi.a libhidapi-libusb.a libhidapi-hidraw.a hidapi hidapi-libusb hidapi-hidraw)
     set(PREFERRED_LIBFTDI libftdi.a ftdi)
     set(PREFERRED_LIBFTDI1 libftdi1.a ftdi1)
-    set(PREFERRED_LIBREADLINE libreadline.a)
-    set(PREFERRED_LIBSERIALPORT libserialport.a)
+    set(PREFERRED_LIBREADLINE libreadline.a readline)
+    set(PREFERRED_LIBSERIALPORT libserialport.a serialport)
     set(PREFERRED_LIBGPIOD libgpiod.a gpiod)
 else()
     set(PREFERRED_LIBELF elf)
```

That should result in an `avrdude` executable binary which is statically linked to `libavrdude`, but dynamically links to system libraries such as `libreadline.so.8`, which appears to be the desired outcome, judging from all the other `PREFERRED_*` definitions in the `USE_STATIC_LIBS` case.

If the fix suggested above is acceptable, here is the pull request: https://github.com/avrdudes/avrdude/pull/1625

**Comment by mcuee** [comment]
Good catch. Thanks.
