### ISSUE TITLE
Writing one-byte files to flash fails

### ISSUE THREAD

**Issue by stefanrueger** [avrdudes/avrdude#1633]
```
$ avrdude -qqc dryrun -p m328p -U flash:w:42:m && echo OK
avrdude warning: verification mismatch
        device 0xff != input 0x2a at addr 0x0000 (error)
avrdude error: verification mismatch
```

A rather rare case, but still, if someone wants to just change/overwrite the first byte of flash it won't work. This problem is programmer and part independent. What should happen is that (at least) 2 bytes are read from flash, the first byte modified and (at least) 2 bytes written back to the device.

**Comment by dl8dtl** [comment]
Well, the flash is organized in 16-bit words, so it doesn't come out as a surprise to me.

**Comment by stefanrueger** [comment]
True; avrdude takes great care that files with an odd number of bytes *can* be written to flash (think data after the application), it's just that one-byte files still fail.
