### ISSUE TITLE
Old `avrdude_message()` can go away

### ISSUE THREAD

**Issue by dl8dtl** [avrdudes/avrdude#1719]
I just noticed that it's not used anymore anywhere.

**Comment by stefanrueger** [comment]
Do you want the new `avrdude_message2()` be renamed to `avrdude_message()` once the old one is removed?

**Comment by mcuee** [comment]
> Do you want the new `avrdude_message2()` be renamed to `avrdude_message()` once the old one is removed?

Hmm, I think it is better not to do that since it will cause confusion. 

We can add a note in `avrdude_message2()` to mention that there was  `avrdude_message()` function  in the history but that was removed since it is no longer in use.

**Comment by dl8dtl** [comment]
> We can add a note in `avrdude_message2()` to mention that there was `avrdude_message()` function in the history but that was removed since it is no longer in use.

I did so on Stefan's PR.
