### ISSUE TITLE
avr_write_mem() does not really write something

### ISSUE THREAD

**Issue by dl8dtl** [avrdudes/avrdude#1720]
When calling `avr_write_mem()` from my Python wrapper, it never writes something.

```
>>> m=ad.avr_locate_mem(p, 'eeprom')
>>> amnt=ad.avr_read_mem(pgm, p, m)
Reading 100 %
>>> print(amnt)
512
>>> m.get(10)
b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
```
=> EEPROM is empty, OK
Now, fill the buffer, and try writing:
```
>>> m.put(b'The quick brown fox jumps over the lazy duck.')
45
>>> m.get(10)
b'The quick '
>>> amnt=ad.avr_write_mem(pgm, p, m, 512, True)
>>> ing   0 %
>>> print(amnt)
512
```
Note the "ing  0 %" - the remainder of the progress report. It returns so fast, no progress visible at all.
Now, read it back:
```
>>> amnt=ad.avr_read_mem(pgm, p, m)
Reading 100 %
>>> m.get(10)
b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
```
=> Nothing written

Seems the logic inside `avr_write_mem()` somehow doesn't trigger any write.

(Hint: `m.put` and `m.get` are Python access methods to `m->buf`, accepting or returning Python `bytes` objects.)

**Comment by stefanrueger** [comment]
I suspect the corresponding `m->tag[]` bytes are not set.

(off-topic: I also suspect the python implementation/wrapper of progress reporting does something else than the AVRDUDE progress reporting as I haven't seen the behaviour that "ing  0 %" is written for the latter.)

**Comment by dl8dtl** [comment]
As I've got that `m->put` method, it could certainly somehow handle setting the tags.

**Comment by stefanrueger** [comment]
> Who is responsible for setting the tags? (and how is it done? :)

Reading in a file for writing sets the tags (to manage holes in files in the Intel hex or Motorola S record format)

**Comment by dl8dtl** [comment]
Yes, the progress reporter is a much simplified version in my test (it's a plain Python callback now).
I guess I have to assign `m->tag[]` in my `m.put()` helper then, yes.

**Comment by dl8dtl** [comment]
Yep, works now:
```
>>> m=ad.avr_locate_mem(p, 'eeprom')
>>> ad.avr_read_mem(pgm, p, m)
Reading 100 %
512
>>> m.get(10)
b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
>>> m.put(b'The quick brown fox jumps over the lazy dog.')
44
>>> ad.avr_write_mem(pgm, p, m, 44)
Writing 100 %
44
>>> ad.avr_read_mem(pgm, p, m)
Reading 100 %
512
>>> m.get(44)
b'The quick brown fox jumps over the lazy dog.'
```

**Comment by dl8dtl** [comment]
All is working.

**Comment by stefanrueger** [comment]
> `m.put` and `m.get` are Python access methods to `m->buf`, accepting or returning Python bytes objects

`m.put` and `m.get` ought to take an address within buffer argument as well in order to provide random access to `m->buf`

**Comment by dl8dtl** [comment]
They do, it is called `offset`. It just defaults to 0.

**Comment by dl8dtl** [comment]
And for `m.put`, the length is taken from the input byte string, while for `m.get`, the length needs to be specified.

**Comment by dl8dtl** [comment]
Remember, this is Python, we can have default values for arguments. :-) (The SWIG wrapper can handle them, even though the C backend functions cannot.)

**Comment by stefanrueger** [comment]
> They do, it is called offset. It just defaults to 0.

Ahh, great.

> Yes, the progress reporter is a much simplified version in my test (it's a plain Python callback now).

In order to support the logic of libavrdude progress reporting, the application-specific `update_progress()` functions should not do anything before a header was provided and they should stop updating on progress as soon as a terminating progress report call was issued. Basically, it's a logic that dances around 
https://github.com/avrdudes/avrdude/blob/34366a6b9d4b489099e0cd9853d1e60098b44a41/src/term.c#L2685-L2686

This needs documentation, and this could be provided at the same time when Issue #1721is dealt with.

**Comment by dl8dtl** [comment]
I think the existing `progress_callback` in my Python test code works basically like that:
```
# very simplified progress callback
global prog_hdr
prog_hdr = ""
def progress_callback(percent: int, etime: float, hdr: str, finish: int):
    if hdr:
        global prog_hdr
        prog_hdr = hdr
    print(f"{prog_hdr} {percent:3d} %", end='\r', file=sys.stderr, flush=True)
    if (percent == 100):
        print("", file=sys.stderr)
```
But that's merely a simplified example right now. There's room for fine-tuning. :-)
