### ISSUE TITLE
Add support for more AVR-DU parts

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#1742]
Microchip has just released a preliminary datasheet revealing more AVR-DU chips.

[datasheet PDF](https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/AVR32-16DU-14-20-28-32-Prelim-DataSheet-DS40002576.pdf)

[datasheet HTML](https://onlinedocs.microchip.com/oxy/GUID-C431CD9B-65A0-4015-871C-58A444612066-en-US-2/GUID-C1FC3A0A-5479-44A0-979B-ACDD6118FAA0.html)

![image](https://github.com/avrdudes/avrdude/assets/3238730/6b88fbf2-4c78-4dcd-b067-564aef007c8e)

CPN | Flash/SRAM | Pin Count | Package Type | Temperature Range | Carrier Type
-- | -- | -- | -- | -- | --
AVR32DU14T-I/SL | 32 KB/4 KB | 14 | SOIC | -40°C to +85°C | Tape & Reel
AVR32DU14-I/SL | 32 KB/4 KB | 14 | SOIC | -40°C to +85°C | Tube
AVR32DU20T-I/REB | 32 KB/4 KB | 20 | VQFN | -40°C to +85°C | Tape & Reel
AVR32DU20-I/REB | 32 KB/4 KB | 20 | VQFN | -40°C to +85°C | Tube
AVR32DU20T-I/SS | 32 KB/4 KB | 20 | SSOP | -40°C to +85°C | Tape & Reel
AVR32DU20-I/SS | 32 KB/4 KB | 20 | SSOP | -40°C to +85°C | Tube
AVR32DU28-I/SP | 32 KB/4 KB | 28 | SPDIP | -40°C to +85°C | Tube
AVR32DU28T-I/SS | 32 KB/4 KB | 28 | SSOP | -40°C to +85°C | Tape & Reel
AVR32DU28-I/SS | 32 KB/4 KB | 28 | SSOP | -40°C to +85°C | Tube
AVR32DU28T-I/STX | 32 KB/4 KB | 28 | VQFN | -40°C to +85°C | Tape & Reel
AVR32DU28-I/STX | 32 KB/4 KB | 28 | VQFN | -40°C to +85°C | Tube
AVR32DU32T-I/PT | 32 KB/4 KB | 32 | TQFP | -40°C to +85°C | Tape & Reel
AVR32DU32-I/PT | 32 KB/4 KB | 32 | TQFP | -40°C to +85°C | Tray
AVR32DU32T-I/RXB | 32 KB/4 KB | 32 | VQFN | -40°C to +85°C | Tape & Reel
AVR32DU32-I/RXB | 32 KB/4 KB | 32 | VQFN | -40°C to +85°C | Tray
AVR16DU14T-I/SL | 16 KB/2 KB | 14 | SOIC | -40°C to +85°C | Tape & Reel
AVR16DU14-I/SL | 16 KB/2 KB | 14 | SOIC | -40°C to +85°C | Tube
AVR16DU20T-I/REB | 16 KB/2 KB | 20 | VQFN | -40°C to +85°C | Tape & Reel
AVR16DU20-I/REB | 16 KB/2 KB | 20 | VQFN | -40°C to +85°C | Tube
AVR16DU20T-I/SS | 16 KB/2 KB | 20 | SSOP | -40°C to +85°C | Tape & Reel
AVR16DU20-I/SS | 16 KB/2 KB | 20 | SSOP | -40°C to +85°C | Tube
AVR16DU28-I/SP | 16 KB/2 KB | 28 | SPDIP | -40°C to +85°C | Tube
AVR16DU28T-I/SS | 16 KB/2 KB | 28 | SSOP | -40°C to +85°C | Tape & Reel
AVR16DU28-I/SS | 16 KB/2 KB | 28 | SSOP | -40°C to +85°C | Tube
AVR16DU28T-I/STX | 16 KB/2 KB | 28 | VQFN | -40°C to +85°C | Tape & Reel
AVR16DU28-I/STX | 16 KB/2 KB | 28 | VQFN | -40°C to +85°C | Tube
AVR16DU32T-I/PT | 16 KB/2 KB | 32 | TQFP | -40°C to +85°C | Tape & Reel
AVR16DU32-I/PT | 16 KB/2 KB | 32 | TQFP | -40°C to +85°C | Tray
AVR16DU32T-I/RXB | 16 KB/2 KB | 32 | VQFN | -40°C to +85°C | Tape & Reel
AVR16DU32-I/RXB | 16 KB/2 KB | 32 | VQFN | -40°C to +85°C | Tray

| Device Name | Signature byte 0 | Signature byte 1 | Signature byte 2 | 
|-------------|------------------|------------------|------------------|
| AVR32DU32   | 0x1E             | 0x95             | 0x3F             |
| AVR32DU28   | 0x1E             | 0x95             | 0x40             |
| AVR32DU20   | 0x1E             | 0x95             | 0x4E             |
| AVR32DU14   | 0x1E             | 0x95             | 0x4F             |
| AVR16DU32   | 0x1E             | 0x94             | 0x38             |
| AVR16DU28   | 0x1E             | 0x94             | 0x39             |
| AVR16DU20   | 0x1E             | 0x94             | 0x3A             |
| AVR16DU14   | 0x1E             | 0x94             | 0x3B             |

**Comment by stefanrueger** [comment]
Best to wait for the .atdf files. We have a couple of ghost parts in `avrdude.conf` that were documented but never materialised:
```
$ grep //AVR src/avrintel.c  | grep -v atdf
  //AVR8EA28                                                  avrdude // Sources
  //AVR8EA32                                                  avrdude // Sources
```

PR #1747 updates the avrintel files to the most recent .atdf files but unfortunately, above AVR-DU parts are not yet there.

**Comment by MCUdude** [comment]
A new AVR-Dx pack has _just_ been released! lots of new DU chips added

https://packs.download.microchip.com/

![image](https://github.com/avrdudes/avrdude/assets/3238730/a8f3d5d4-93f4-488e-93af-a69ab411252b)
