### ISSUE TITLE
Add support for emscripten

### ISSUE THREAD

**Issue by koen1711** [avrdudes/avrdude#1743]
I made a fork of avrdude that works with emscripten, would you be interested in a fix upstream that allows support for this and maybe be used within Arduino?

**Comment by mcuee** [comment]
Thanks, please help to provide more details about the fork and why you need to use emscripten. Arduino already supports the use of avrdude.

**Comment by koen1711** [comment]
Using this technique I managed to get an uploader for an Arduino in the browser without any necessary installs, like Arduino Create Agent. Please note that the compilation still runs on a backend.

**Comment by mcuee** [comment]
@koen1711 

You can always create a pull request so that the reviewers can review. PRs will be welcome.

**Comment by koen1711** [comment]
Yes I will, but I first wanted to investigate if avrdude/Arduino would be interested in such additions.q

**Comment by stefanrueger** [comment]
@koen1711 Yes, the project is interested in user contributions. Whether or not a PR is going to be accepted will depend on its scope, complexity, maintainability, code quality and whether it might be used reasonably often. But yes, we're look at it with an open mind.

**Comment by stefanrueger** [comment]
Just checking whether you want to keep this issue open @koen1711

**Comment by stefanrueger** [comment]
Just checking whether you want to keep this issue open @koen1711

**Comment by stefanrueger** [comment]
Closing as we have answered the question
