### ISSUE TITLE
avrdude documentation typo(s) attemps

### ISSUE THREAD

**Issue by Daniii438** [avrdudes/avrdude#1852]
I have noticed that the documentation has a couple of Typos with the word "attempts"

Just spend 30 mins trying to figure out why "avrdude.exe -x attemps=2 -c..." does not work, untill I noticed the missing "t" in attempts in the documentation, where I copied the command from. 

I´m not sure how to fix it myself, so if anyone could fix it, that would be very nice of you :)

Thanks

**Comment by stefanrueger** [comment]
@Daniii438 Thanks for making us aware! Fixed now in git main. The documentation of the next release won't have *these* typos.
