### ISSUE TITLE
[bug #38199] Feature request: Clarify 'initialization failed' error message

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#278]
n.st <None>
Tue 29 Jan 2013 11:40:04 PM UTC

It might be helpful (especially for novice users) to clarify the error message
avrdude: initialization failed, rc=-2
Double check connections and try again, or use -F to override this check.

In its current form, it doesn't really bring across that this will most likely be a problem with the AVR not being powered, connected or clocked correctly. People might blame their programmer instead, even though it is far less likely to be broken than the AVR, its connections or clock source.

Also, when using a programmer that allows the user to set a custom SPI clock frequency (e.g. the buspirate), the user should be reminded that the AVR's clock frequency needs to be less than a quarter of the SPI frequency it is programmed with. This might be appropriate to be mentioned in the manpage, and putting it into the rc=-2 error message would be helpful, too.

This issue was migrated from https://savannah.nongnu.org/bugs/?38199

**Comment by mcuee** [comment]
Second part is already docemented.
Ref: https://avrdudes.github.io/avrdude/7.0/avrdude_39.html#Troubleshooting
