### ISSUE TITLE
[bug #38792] Add missing XMEGA parts

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#285]
rmann <None>
Sun 21 Apr 2013 06:16:57 AM UTC

I happen to be using these parts, and they're not in avrdude. I seem to be able to use x256a3 and x64a4, but I don't yet know if I'm missing some crucial difference.

ATxmega256A3U family
ATxmega64D4 family

This issue was migrated from https://savannah.nongnu.org/bugs/?38792

**Comment by MCUdude** [comment]
These parts and their entire families are present in the current avrdude.conf file.
