### ISSUE TITLE
[bug #40144] flash config for ATtiny1634 is wrong

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#306]
Tobias Diedrich <None>
Sun 29 Sep 2013 11:41:38 PM UTC

The addressing config for flash programming is off ( loadpage_lo / loadpage_hi / writepage).

According to the datasheet it is 512 32-word pages,
so it needs to be a3-0 for loadpage and a12-a4 for writepage.

The sympton is verification failures and on reading back the flash blocks of 32 words corrupted data followed by 3 x 32 words of 0xff.

After changing it to:
loadpage_lo     = " 0 1 0 0 0 0 0 0",
" 0 0 0 x x x x x",
" x x x x a3 a2 a1 a0",
" i i i i i i i i";

loadpage_hi     = " 0 1 0 0 1 0 0 0",
" 0 0 0 x x x x x",
" x x x x a3 a2 a1 a0",
" i i i i i i i i";

writepage       = " 0 1 0 0 1 1 0 0",
" 0 0 0 a12 a11 a10 a9 a8",
" a7 a6 a5 a4 x x x x",
" x x x x x x x x";
it now works fine for me.

This issue was migrated from https://savannah.nongnu.org/bugs/?40144

**Comment by MCUdude** [comment]
@dl8dtl this issue can be closed, since the fix is already present in Avrdude.conf.in
