### ISSUE TITLE
[bug #44252] Build fails when no libusb is detected.

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#374]
Georg Bisseling <spam@bisseling.de>
Sat 14 Feb 2015 07:34:11 PM UTC

The build fails because of declarations for dfu_init and dfu_open in dfu.h that differ from the implementation in dfu.c.

The reaon is quite obvious.

Today's sources. Build to version 6.1.

This issue was migrated from https://savannah.nongnu.org/bugs/?44252

**Comment by MCUdude** [comment]
I thought libusb was required to compile Avrdude?

**Comment by mariusgreuel** [comment]
> I thought libusb was required to compile Avrdude?

It actually does compile without libusb. Has been fixed though, thank you for pointing this out!
