### ISSUE TITLE
[bug #44541] Target not running after avrdude invocation

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#378]
Michael Lipp <mnl@mnl.de>
Sat 14 Mar 2015 01:56:35 PM UTC

If the OCDEN fuse is set in my m128, I find that after the invocation of avrdude, the mcu is always in stopped mode. The attached patch fixes this.

[file #33342: avrdude-ensure-running.patch](https://savannah.nongnu.org/bugs/download.php?file_id=33342)

This issue was migrated from https://savannah.nongnu.org/bugs/?44541

**Comment by mcuee** [comment]
@MCUdude 
Not so sure if you can test this with an m128 or m1284.

**Comment by mcuee** [comment]
Based on the reports here by @MCUdude with m128, this can be closed.
* https://github.com/avrdudes/avrdude/issues/377#issuecomment-1160724376
