### ISSUE TITLE
[bug #45256] Raspberry Pi sysfs bug workaround for linuxgpio driver

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#386]
Nick Sayer <None>
Fri 05 Jun 2015 05:10:31 AM UTC

avrdude 6.1 includes the 'inuxgpio' driver for Raspberry Pi GPIO.

There appears to be some sort of race condition bug in sysfs that results in the permissions for the gpio direction file being incorrect when "sufficient" time is not allowed for the creation process to complete. As a workaround, a small delay can be introduced between the export operations and the remaining setup.

[file #34162: patch.txt](https://savannah.nongnu.org/bugs/download.php?file_id=34162)

This issue was migrated from https://savannah.nongnu.org/bugs/?45256

**Comment by mcuee** [comment]
#917 has been merged. I will close this as well.

Please re-open if you encounter similar issues. Thanks.
