### ISSUE TITLE
[bug #47043] Support for TinCan Tools Flyswatter 2

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#407]
Russ Dill <russ.dill@gmail.com>
Mon 01 Feb 2016 10:09:13 PM UTC

The Flyswatter2 is a FT2232H based JTAG programmer. It can be used to program AVRs, but it needs a buff pin set. The attached programmer fragment makes that possible.

[https://www.tincantools.com/wiki/Flyswatter2](https://savannah.nongnu.orghttps://www.tincantools.com/wiki/Flyswatter2)

[file #36230: .avrduderc](https://savannah.nongnu.org/bugs/download.php?file_id=36230)

This issue was migrated from https://savannah.nongnu.org/bugs/?47043

**Comment by mcuee** [comment]
This seems to be a pretty popular FTDI based debugger/programmer, not so sure if any user can test this out.

**Comment by mcuee** [comment]
@russdill

Just wondering if you are still interested in this issue. If yes, please create a new PR for that. Take note that there are some changes in the latest avrdude.conf.in.
```
mosi --> sdo
miso --> sdi
```

**Comment by stefanrueger** [comment]
@russdill @mcuee Always best to add a canonical form of the entry; you get this by 
 - Adding the entry provisionally to `avrdude.conf.in` and install it
 - Then using the output of `avrdude -cflyswatter2/s` to replace the provisional entry in `avrdude.conf.in`
