### ISSUE TITLE
[bug #47776] Wrong Device ID for xMega16C4 / xMega32C4

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#415]
ThiloA <None>
Sun 24 Apr 2016 01:56:21 PM UTC

Hi

according to

[http://www.atmel.com/Images/Atmel-8493-8-and-32-bit-AVR-XMEGA-Microcontrollers-ATxmega16C4-ATxmega32C4_Datasheet.pdf](https://savannah.nongnu.orghttp://www.atmel.com/Images/Atmel-8493-8-and-32-bit-AVR-XMEGA-Microcontrollers-ATxmega16C4-ATxmega32C4_Datasheet.pdf)

device ids should be

ATxmega16C4: 1E 94 43
ATxmega32C4: 1E 95 44

But in avrdude.conf.in both ids are interchanged:
...
desc	= "ATxmega16C4";
signature	= 0x1e 0x95 0x44;
...
desc	= "ATxmega32C4";
signature	= 0x1e 0x94 0x43;
...

Regards
ThiloA

This issue was migrated from https://savannah.nongnu.org/bugs/?47776

**Comment by MCUdude** [comment]
Fix has been applied to Avrdude.conf.in. Issue can ble closed
