### ISSUE TITLE
[bug #48237] ATmega328PB not supported

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#424]
kaz <None>
Thu 16 Jun 2016 05:56:07 AM UTC

I added the following lines into avrdude.conf and worked for me.

part parent "m328"
id			= "m328pb";
desc		= "ATmega328PB";
signature		= 0x1e 0x95 0x16;

ocdrev              = 1;

memory "efuse"
size = 1;
min_write_delay = 4500;
max_write_delay = 4500;
read = "0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0",
"x x x x x x x x o o o o o o o o";

write = "1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0",
"x x x x x x x x x x x x i i i i";
;

;

This issue was migrated from https://savannah.nongnu.org/bugs/?48237

**Comment by MCUdude** [comment]
Issue can be closed, since ATmega324PB support already is present
