### ISSUE TITLE
[bug #48457] avrdude problem with chip CH340G

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#426]
PSL <slansky@usa.net>
Sun 10 Jul 2016 01:48:11 PM UTC

I have a clone of Arduino Nano V3 with chip CH340G and I see a protocol problem. I use my Arduino clone as ISP STK500v1, it is loaded with example ArduinoISP that is distributed with Arduino IDE.

[https://www.arduino.cc/en/Tutorial/ArduinoISP](https://savannah.nongnu.orghttps://www.arduino.cc/en/Tutorial/ArduinoISP)

Avrdude works fine with ArduinoISP when it runs at Arduino with FTDI chip but fails with protocol error at Arduino with CH340G chip. I run it at Ubuntu Linux. Command to test:

# avrdude -c stk500v1 -P /dev/ttyUSB0 -b 19200 -p m328p -vvvv

I have found that when I add more calls "stk500_drain" to stk500.c, I remove this problem. I attach a simple patch.

BTW, man can find more reports on this problem with Google.

[file #37792: stk500_drain.diff](https://savannah.nongnu.org/bugs/download.php?file_id=37792)

This issue was migrated from https://savannah.nongnu.org/bugs/?48457

**Comment by mcuee** [comment]
I believe this issue has been fixed and I do not have issues to flash my Arduino Uno clone with CH340.
