### ISSUE TITLE
[bug #48460] page mode ignores switch paged=no

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#427]
PSL <slansky@usa.net>
Sun 10 Jul 2016 10:35:04 PM UTC

avrdude 6.3.

This is an example of CPU configuration, I wanted to disable page mode to test something new:

memory "flash"
size            = 4096;
paged           = no;
page_size	= 256;
num_pages	= 16;

I use STK500v1 compatible programmer, ArduinoISP.
avrdude starts to program flash memory in page mode, it ignores option paged=no. I has to comment out entries page_size and num_pages to program flash memory in byte mode.
From my point of view, this is a bug.

This issue was migrated from https://savannah.nongnu.org/bugs/?48460

**Comment by MCUdude** [comment]
If you're dealing with a microcontroller which as paged flash memory, you can't just set `pages = no` and expect it to work.
There are a few legacy devices that from what I'm aware of doesn't has a page oriented flash memory. Some of them are:

* ATtiny11
* ATtiny12
* ATtiny15
* ATtiny28
* AT90S8515
* AT90S8535

I'm sure there are others too.
