### ISSUE TITLE
[bug #50103] [windows 7] avrdude 6.3 doesn't exit cleanly and dialog "avrdude.exe has stopped working" pops up

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#442]
maredsous10 <maredsous10@gmail.com>
Fri 20 Jan 2017 04:06:13 PM UTC
Programmer hardware: Olimex AVR ISP MKII
Device type: ATTINY4

I am using an Olimex AVR ISP MKII, Attiny4, Windows 7 64bit and AVRDude 6.3 (from [http://download.savannah.gnu.org/releases/avrdude/](https://savannah.nongnu.orghttp://download.savannah.gnu.org/releases/avrdude/)).

The following is run from the command line:

avrdude -c avrispmkII -p attiny4 -U flash:w:program.hex

The erase, programming, and verification runs successfully and the attiny4 operates as expected.

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e8f0a (probably t4)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "program.hex"
avrdude: input file program.hex auto detected as Intel Hex
avrdude: writing flash (144 bytes):

Writing | ################################################## | 100% 0.34s

avrdude: 144 bytes of flash written
avrdude: verifying flash memory against program.hex:
avrdude: load data flash data from input file program.hex:
avrdude: input file program.hex auto detected as Intel Hex
avrdude: input file program.hex contains 144 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.07s

avrdude: verifying ...
avrdude: 144 bytes of flash verified

avrdude done.  Thank you.

When AVRDUDE gets to "avrdude done.  Thank you.", avrdude hangs and a dialog pops up saying "avrdude.exe has stopped working".

Any ideas on this issue?   I assume avrdude is getting hung up and not cleanly exiting.

This issue was migrated from https://savannah.nongnu.org/bugs/?50103

**Comment by mariusgreuel** [comment]
Multiple bugs corrected, please try the current version.
