### ISSUE TITLE
[bug #50701] Feature Request: reinstall erase/rewrite cycle counter

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#451]
Michael H. <de.bug@safe-mail.net>
Sun 02 Apr 2017 07:19:13 AM UTC

Please reinstall the erase/rewrite cycle counter. We still have to use avrdude 5.11 to use this.

This issue was migrated from https://savannah.nongnu.org/bugs/?50701

**Comment by MCUdude** [comment]
I don't think it's going to happen. Please fork the project and add it if this is a feature you absolutely depend on.
