### ISSUE TITLE
[bug #50777] aclocal fails with "couldn't open directory 'm4': No such file or directory"

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#452]
Yegor Yefremov <None>
Mon 10 Apr 2017 10:57:36 AM UTC

New automake versions fails. if m4 folder is missing. There is a rather comprehensive description/discussion of this issue here [1]. I'm experiencing this issue in Buildroot. Creating an empty
m4 folder in SVN tree would be the least invasive solution.

[1] [https://bugzilla.redhat.com/show_bug.cgi?id=901333](https://savannah.nongnu.orghttps://bugzilla.redhat.com/show_bug.cgi?id=901333)

This issue was migrated from https://savannah.nongnu.org/bugs/?50777

**Comment by yegorich** [comment]
This one is now obsolete and can be closed.

**Comment by mariusgreuel** [comment]
Use CMake instead
