### ISSUE TITLE
[bug #51416] Bug when 'n' is typed after "Would you like this fuse to be changed back? [y/n] "

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#457]
Xavier (fjrg76) <None>
Sat 08 Jul 2017 01:18:52 AM UTC

Nothing happens when n is typed in such situation. Just blank lines as long as you type "enter" or any other key. The only way to exit the program is with "Ctrl+C".

I digged into the source code (both 6.2 which is installed in my system, and 6.3) and there is nothing to do when "n" is typed. Something should happen in this situation, so the user knows what's going on. Here is the code snippet, if it worhs:

/* Now check what fuses are against what they should be */
if (safemodeafter_efuse != safemode_efuse) {
fuses_updated = 1;
avrdude_message(MSG_INFO, "%s: safemode: efuse changed! Was %x, and is now %x\n",
progname, safemode_efuse, safemodeafter_efuse);

/* Ask user - should we change them */
if (silentsafe == 0)
safemode_response = terminal_get_input("Would you like this fuse to be changed back? [y/n] ");
else
safemode_response = yes;
if (tolower((int)(safemode_response[0])) == 'y') { ///// THERE IS NO 'ELSE'

/* Enough chit-chat, time to program some fuses and check them */
if (safemode_writefuse (safemode_efuse, "efuse", pgm, p,
10) == 0) {
avrdude_message(MSG_INFO, "%s: safemode: and is now rescued\n", progname);
}
else {
avrdude_message(MSG_INFO, "%s: and COULD NOT be changed\n", progname);
failures++;
}
}
}

Thanks!!

This issue was migrated from https://savannah.nongnu.org/bugs/?51416

**Comment by MCUdude** [comment]
Avrdude safemode has been removed from the upstream version
