### ISSUE TITLE
[bug #51629] avrdude.exe: usbdev_open(): did not find any USB device "usb"

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#460]
R0b0t1 <None>
Mon 31 Jul 2017 05:10:34 PM UTC
Programmer hardware: AVR ISP Mk II
Device type: m328p

Using:

avrdude -p m328p -c avrisp2 -P usb -D -U lfuse:w:0xe3:m -U hfuse:w:0xd8:m -U efuse:w:0xfd:m

I also was attempting to do "-c avrispmkII". This is the version as shipped by WinAVR; I have been experiencing this issue for multiple years. I am trying to avoid installing Atmel Studio because I don't like it. The firmware on the AVR ISP Mk II has been upgraded, has this introduced a breaking change?

libusb drivers have been installed with the Zadig tool ([http://zadig.akeo.ie/](https://savannah.nongnu.orghttp://zadig.akeo.ie/)) though I have tried to install them manually using libusb-win32. As far as I know installation was successful in both cases.

I tried to reproduce this with a self-compiled 6.3 version, but I can't get the build system to compile in support for USB programmers despite the configure script detecting various libusb functions.

This issue was migrated from https://savannah.nongnu.org/bugs/?51629

**Comment by mariusgreuel** [comment]
See https://github.com/avrdudes/avrdude/wiki/Troubleshooting-USB-devices-in-Windows
