### ISSUE TITLE
[bug #51664] compare of unused efuse bits fail

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#461]
Martin Pischky <None>
Sat 05 Aug 2017 09:53:11 AM UTC
Programmer hardware: avrispv2 or avrdude_isp
Device type: Atmega328P

With -U efuse:w:0x05:m we get the meassge:
~~~~~
Writing | ################################################## | 100% 0.02s

avrdude.exe: 1 bytes of efuse written
avrdude.exe: verifying efuse memory against 0x05:
avrdude.exe: load data efuse data from input file 0x05:
avrdude.exe: input file 0x05 contains 1 bytes
avrdude.exe: reading on-chip efuse data:

Reading | ################################################## | 100% -0.00s

avrdude.exe: verifying ...
avrdude.exe: verification error, first mismatch at byte 0x0000
0xfd != 0x05
avrdude.exe: verification error; content mismatch
~~~~~

The difference are the undefined bits in the efuses (3 to 7).

As far as I understand from datasheet and use with atmel tools these should be spezified as "1" but for older versions of avrdude (5.1? to 6.1) these had to be set to "0" to avoid abort on programming. Now on switching from AVRDude 6.1 to 6.3 this is not working anymore and the programming gets aborted and the fuses remain unchanged.

I guess this may be related to **[bug #22248](https://savannah.nongnu.org/bugs/?22248)** (and #21954).

From SVN I can see that with revision r1335 the part definition has been changed (part/id="m328"/memory "efuse"/read) for the bits 3 to 7 from "x" to "o". I did not know what the effect of this change is.

I would suggest that these bits are ignored in the compare to be compatible with older versions of AvrDude.

This issue was migrated from https://savannah.nongnu.org/bugs/?51664

**Comment by MCUdude** [comment]
This is currently a non-issue. Unused bits should be set to 1, but Avrdude does it for you anyways, and give you a warning.
Here's the output when I try to write 0x05 as efuse:

```
$ ./avrdude -C avrdude.conf -c usbasp -p atmega328p -Uefuse:w:0x05:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file "0x05"
avrdude: writing efuse (1 bytes):

Writing |                                                    | 0% 0.00s ***failed;  
Writing | ################################################## | 100% 0.03s

avrdude: 1 bytes of efuse written
avrdude: verifying efuse memory against 0x05:

Reading | ################################################## | 100% 0.00s

avrdude: WARNING: ignoring mismatch in unused bits of "efuse"
         (0xfd != 0x05). To prevent this warning set unused bits
         to 1 when writing (double check with your datasheet first).
avrdude: 1 bytes of efuse verified

avrdude done.  Thank you.
```
