### ISSUE TITLE
[bug #53180] missing programmer or bad -P option argument doesn't result in error message

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#471]
Britton Kerin <britton.kerin@gmail.com>
Sat 17 Feb 2018 10:59:23 PM UTC
Programmer hardware: AVR ISPmkII
Device type: Mega 328P

This command:

avrdude -c avrispmkII -p m328p -P usb:090200198577 -U hfuse:r:-:h

issued when there is no avrispmkII connected, yields only this message on stderr:

avrdude done.  Thank you.

avrdude does exit with a non-zero code in this case, but it should also be able to give an informative error message.

This command:

avrdude -c avrispmkII -p m328p -P usb:090200198577 -U hfuse:r:-:h

issued when there is no avrispmkII with serial number 090200198577 connected, does the same thing.

This issue was migrated from https://savannah.nongnu.org/bugs/?53180

**Comment by MCUdude** [comment]
Similar issue to #813. Will be resolved when #814 gets merged.
