### ISSUE TITLE
[bug #54514] Control stk500 retry attempts

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#480]
Cameron Tacklind <None>
Wed 15 Aug 2018 12:19:37 AM UTC

Hello,

I am trying to build avrdude into a script for assembly line style programing of a bunch of arduino boards. One of the things I like to do is to just try the connection continuously until it succeeds and only then try the full programming. This way operators don't even need to press a key on the programming station. Unfortunately the stk500 mode (which arduino is based on) has a hard coded MAX_SYNC_ATTEMPTS. Is there a way to make this configurable? I'd like to set it to 1. Also I'd like to set the timeout time to be shorter if possible.

Please see [https://arduino.stackexchange.com/questions/24784/avoid-the-10-attempts-of-avrdude-when-programmer-is-not-responding](https://savannah.nongnu.orghttps://arduino.stackexchange.com/questions/24784/avoid-the-10-attempts-of-avrdude-when-programmer-is-not-responding) for another discussion of this issue.

Thanks.

This issue was migrated from https://savannah.nongnu.org/bugs/?54514

**Comment by MCUdude** [comment]
Added in #854.

Usage:
```
-x attempts=5
```
