### ISSUE TITLE
[bug #57453] [PATCH] fix reference to nonexistant -m option by changing to -U

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#497]
Britton Kerin <britton.kerin@gmail.com>
Thu 19 Dec 2019 10:32:32 PM UTC
Programmer hardware: all
Device type: all

as subject says

[file #48094: 0001-Change-reference-to-m-option-to-U-option.patch](https://savannah.nongnu.org/bugs/download.php?file_id=48094)

This issue was migrated from https://savannah.nongnu.org/bugs/?57453

**Comment by avrdude-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Sat 06 Nov 2021 10:44:45 PM UTC

Fixed in r1456, thanks!

**Comment by MCUdude** [comment]
Issue can probably be closed
