### ISSUE TITLE
[patch #5038] bugfix for patch 4901 (that is patch 4 fastwrite&verify)

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#565]
Thu 13 Apr 2006 03:51:01 PM UTC

Revision: 8
Author: AlexRayne
Date: 19:22:55, 13 àïðåëÿ 2006 ã.
Message:
(rus)
*ôèêñ îøèáêè ðàáîòû â ðåæèìå àâð910 ñ íåñòðàíè÷íûìè äåâàéñàìè - äëÿ íèõ ðàçìåð ñòðàíèöû áûë=0 ÷òî ïðèâîäèëî ê ïîâèñàíèþ ñêàíåðà ïóñòîãî ìåñòà\çàíÿòûõ áëîêîâ
+äîáàâëåíû êîììåíòû îòëàäî÷íûå
(eng)
*bugfix of work in avr910 mode 4 nonpaged devices - page_size was=0, this cause to hanging scanner freespace\nonemty pages
+debug messages added

Modified : /avr.c
Modified : /avr910.c
Modified : /avrpart.c
Modified : /butterfly.c
Modified : /config_gram.c
Modified : /config_gram.y
Modified : /main.c
Modified : /pgm.c
Modified : /term.c

[file #9778: avrdude_4901bugfix.diff.zip](https://savannah.nongnu.org/patch/download.php?file_id=9778)

This issue was migrated from https://savannah.nongnu.org/patch/?5038

**Comment by MCUdude** [comment]
I'm closing this issue because the code it tries to fix has largely been replaced by other patches over the years. If you believe similar issues still exist, please open a new issue, and we'll be happy to look at it with new eyes.
