### ISSUE TITLE
[patch #7368] GoodFET support

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#620]
Mon 01 Nov 2010 08:00:09 PM UTC

This patch adds support for Travis Goodspeed's GoodFET. The GoodFET is an open-source programming adapter that can be built for roughly $20 worth of parts. See [http://goodfet.sf.net](https://savannah.nongnu.orghttp://goodfet.sf.net) for details.

[file #21894: avrdude.patch](https://savannah.nongnu.org/patch/download.php?file_id=21894)

This issue was migrated from https://savannah.nongnu.org/patch/?7368

**Comment by avrdude-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Wed 17 Aug 2011 02:27:47 PM UTC

Please don't forget to submit documentation patches.

I just added a peramble to the patch tracker submission form
explaining some details about our documentation.

Thanks for your contribution!

**Comment by mcuee** [comment]
Not so sure if GoodFET is still popular or not.
http://goodfet.sourceforge.net/
https://github.com/travisgoodspeed/goodfet/
