### ISSUE TITLE
[patch #8591] Implement fragmentation in jtag3

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#691]
Wed 07 Jan 2015 02:58:25 PM UTC

The current code does not support to split the transaction is smaller fragments.
This lead the programming with AVR ICE falling back to byte per byte programming instead of page based programming.

This is slow and leads to corruption on our devices.

This implement the proper fragmentation of the transactions so the programming operation is using a page-based method.

[file #32778: avrice_fragment_fix.patch](https://savannah.nongnu.org/patch/download.php?file_id=32778)

This issue was migrated from https://savannah.nongnu.org/patch/?8591

**Comment by avrdude-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Tue 16 Feb 2016 10:07:48 PM UTC

Thanks for the feedback!
