### ISSUE TITLE
[patch #9004] DTR auto-reset does not work with Arduino Pro Mini

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#708]
Mon 16 May 2016 12:22:03 AM UTC

The DTR line is held the whole time programming an Arduino is attempted.

As pointed out on the mailing list the onboard USB-TTL on Uno is connected to the AtMega reset pin through a capacitor so this can work for Uno.

On Pro Mini there is only a reset pin that you can connect to an external USB-TTL and normally there is no capacitor so DTR has to be released before programming is attempted. Otherwise the Pro Mini stays in reset the whole time and programming fails.

This also fixes **[bug #46005](https://savannah.nongnu.org/bugs/?46005)**

For compatibility the old behavior is used on every other communication attempt but this may be superfluous.

Tested with Chinese Uno and Pro Mini

[file #37171: invert_dtr.patch.txt](https://savannah.nongnu.org/patch/download.php?file_id=37171)

This issue was migrated from https://savannah.nongnu.org/patch/?9004

**Comment by MCUdude** [comment]
I don't think it's a good idea to touch the auto-reset logic.

The [Arduino Pro Mini](https://www.arduino.cc/en/pmwiki.php?n=Main/ArduinoBoardProMini) do have a capacitor in series on the reset line, so it doesn't matter if DTR stays low or high during programming. See the [schematics](https://www.arduino.cc/en/uploads/Main/Arduino-Pro-Mini-schematic.pdf).

[The Arduino *Mini*](https://docs.arduino.cc/retired/boards/arduino-mini-05-without-header) on the other hand doesn't have any auto-reset circuity, and the DTR line is for some reason connected to pin PD7. see the [schematics](https://www.robotiksistem.com/arduino_mini_schematic05.pdf).
Auto reset on this board will probably never work.

I'm not aware of any Pro Mini board that doesn't have a capacitor in series with the reset line, other than the retired Arduino Mini board.
