### ISSUE TITLE
[patch #10149] Add support for Micronucleus bootloader

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#760]
Sun 28 Nov 2021 10:04:33 PM UTC

This patch adds support for the Micronucleus bootloader:
 [https://github.com/micronucleus/micronucleus](https://savannah.nongnu.orghttps://github.com/micronucleus/micronucleus)

Typically command-line usage is
avrdude -c micronucleus -p t85 -x wait -V -U flash:w:main.hex:i

Note that the udev rules need to be changed, too:

# Micronucleus Bootloader
SUBSYSTEM=="usb", ATTR{idVendor}=="16d0", ATTR{idProduct}=="0753", TAG+="uaccess"

Let me know what you think.

[file #52372: avrdude-micronucleus-v1.patch](https://savannah.nongnu.org/patch/download.php?file_id=52372)

This issue was migrated from https://savannah.nongnu.org/patch/?10149

**Comment by mariusgreuel** [comment]
I am putting this patch in a separate PR.
