### ISSUE TITLE
[patch #10150] Add support for Teensy bootloader

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#761]
Sun 28 Nov 2021 10:17:31 PM UTC

This patch adds support for the Teensy HalfKay bootloader:
 [https://www.pjrc.com/teensy/halfkay_protocol.html](https://savannah.nongnu.orghttps://www.pjrc.com/teensy/halfkay_protocol.html)

This programmer supports the AVR devices only:
- Teensy 1.0 (AT90USB162)
- Teensy 2.0 (ATmega32U4)
- Teensy++ 1.0 (AT90USB646)
- Teensy++ 2.0 (AT90USB1286)

Typically command-line usage is
avrdude -c teensy -p m32u4 -x wait -V -F -U flash:w:main.hex:i

The -V switch is required because the bootloader does not support reading.

Also, on my Linux box, libhidapi does not return the proper HID usage page, which is used by the bootloader to identify devices. When a HID usage of zero is reported, the programmer defaults to a zero signature, which then requires the -F switch. Not sure whether there is a Linux libhidapi implementation that actually works. Windows works correctly.

Note that the udev rules need to be changed, too:

# Teensy Bootloader
SUBSYSTEM=="usb", ATTR{idVendor}=="16c0", ATTR{idProduct}=="0478", TAG+="uaccess"

Let me know what you think.

[file #52373: avrdude-teensy-v1.patch](https://savannah.nongnu.org/patch/download.php?file_id=52373)

This issue was migrated from https://savannah.nongnu.org/patch/?10150

**Comment by mariusgreuel** [comment]
I am putting this patch in a separate PR.
