### ISSUE TITLE
Remove all calls to exit(3) from libavrdude library functions

### ISSUE THREAD

**Issue by dl8dtl** [avrdudes/avrdude#774]
(Previously, this had been marked as a "task" on Savannah, with nobody actually backing it.)
Quite some time ago, all the backend functionality of AVRDUDE had been moved out into libavrdude. The idea behind that was that the current `src/main.c` just describes *one* possible frontend, so it could be e.g. accompanied by a kind of GUI frontend as well.
However, some of the historic implementations gratuitously call `exit()` in case of a failure. This is fatal for a GUI application, which rather would prefer to give the user a kind of graphical response of the failure. Thus, call calls to `exit()` need to be converted into returning (and handling) an error code instead.

**Comment by mcuee** [comment]
Interesting background for the libavrdude. 

In order for this idea to work, #952 (#954 is the same for Windows) needs to be fixed. The main problem is Windows.
* #952 
* #954
