### ISSUE TITLE
CMake compiled binaries lack debug symbols

### ISSUE THREAD

**Issue by dl8dtl** [avrdudes/avrdude#824]
Autoconf/automake always call the compiler with -g.
Apparently, CMake-generated Makefiles don't.
At least on Unix-like systems,. there hasn't been a reason to turn off debugging symbols even when optimization is enabled for decades now; both settings do not contradict each other. Stripping debugging symbols on installation is easy, adding debugging symbols later is impossible.
So, that "classic" distinction between "Release" vs. "Debug" is basically irrelevant on Unix-like systems. Best practice is to *always* enable optimizations (nobody wants pessimized code), and *always* compile with debug symbols.

**Comment by mariusgreuel** [comment]
Have you tried CMAKE_BUILD_TYPE=RelWithDebInfo?

See https://github.com/avrdudes/avrdude/blob/main/.github/workflows/build.yml

**Comment by dl8dtl** [comment]
> Have you tried CMAKE_BUILD_TYPE=RelWithDebInfo?

No.
Can we somehow make that the default?

**Comment by dl8dtl** [comment]
Well, as a first shot, it would be useful to document that in the Wiki instead of "Release".
As nobody can memorize that stuff, people are probably going to copy&paste it from the Wiki instructions anyway. ;-)

*****

OK, works.

**Comment by dl8dtl** [comment]
https://www.kitware.com/cmake-and-the-default-build-type/

Any opinions on using that to set the default build type to RelWithDebInfo?

**Comment by mariusgreuel** [comment]
> Any opinions on using that to set the default build type to RelWithDebInfo?

I don't know.

- This code from the blog works only for built-systems such as make.
- The build type is a preference (I prefer Debug), so I would rather not change the defaults.
- There are probably other options you need (see the build action).

On Linux, I set up an alias for building avrdude, on Windows I use a json configuration file to switch between the build types and architectures.

**Comment by dl8dtl** [comment]
OK, two suggestions:

* for Unix-like sytems, we can safely the Wiki instructions to use RelWithDebInfo; doesn't lose any performance but allows for debugging
* also, we could provide a .sh script assisting the build – after all, it's a bit more to memorize than the old `./configure; make` now (I can handle that)
* no idea whether you'd like to add something similar for Windows builds

**Comment by mariusgreuel** [comment]
> we could provide a .sh script assisting the build

I like that solution, because we do not need to change the CMake defaults then. Actually, that is what I am doing, too, when building in Windows. I always work on a branch that has extra files and changes, that I simply rebase on top of the avrdude main branch.

I think a shell script for building in Un*x will be useful for others too, plus you can add other configuration options, too.

**Comment by dl8dtl** [comment]
As the Wiki has already been updated, this one can be closed.

PR #835 will then provide a Unix build script as well.
