### ISSUE TITLE
USBasp returns ERANGE for unknown error

### ISSUE THREAD

**Issue by dl8dtl** [avrdudes/avrdude#848]
When encountering an unknown error code, the USBasp code returns ERANGE, which translates into the text "Result too large".
That does not make any much sense.

**Comment by MCUdude** [comment]
I've never had any issues with USBasp. How can the issue be reproduced?

**Comment by dl8dtl** [comment]
A friend of mine just caught that one. The reason is not yet clear, maybe a bug in FreeBSD 13. libusb eventually returns `LIBUSB_ERROR_UNKNOWN` which the USBasp code then translates into "Result too large".
Whatever it is, just throwing `ERANGE` for any undecided error is utter nonsense.

**Comment by dl8dtl** [comment]
Closed by PR #850
