### ISSUE TITLE
Make the "Homepage" reference this GitHub

### ISSUE THREAD

**Issue by cinderblock** [avrdudes/avrdude#867]
I just found out that AVRDUDE has moved to GitHub (Thank you! Savannah, while I'm sure great in its day, doesn't make it easy to contribute or understand what's going on).

The only way I found this was by trying to submit a bug and noticing that Savannah's was disabled. I had to dig into the mailing list archives slightly to notice that this project had moved.

I see that the Summary page does have a small note about moving to GitHub, but I only saw that after looking for it.

I think the "homepage" (https://www.nongnu.org/avrdude/) needs a prominent reference to this GitHub repo. That page is still highly ranked on search engines and I expect many avrdude users will otherwise miss the move to GitHub if not otherwise mentioned.

**Comment by dl8dtl** [comment]
I've updated the Web page, changing the main URL, and mention the move in the history section.
