### ISSUE TITLE
Make the terminal 'write' functionality more useful

### ISSUE THREAD

**Issue by MCUdude** [avrdudes/avrdude#879]
The terminal mode is really handy if you have a target where you want to just check something or do minor changes. However, I feel like the 'write' functionality has more potential.

The current syntax is this:
`write <memtype> <addr> <byte1> <byte2> ... <byteN>`

Features that would be neat to have:

```
# Fill user defined memory section with a known value (three dots as part of the syntax)
# write <memtype> <start addr> <length> <byte to write to all memory locations> <...> 

# example
write eeprom 0x40 0x10 0x00 ...
```

```
# Write strings with \0 at the end
# write <memtype> <start addr> <string in quotes>

# Example (writes Hello World!\0 to EEPROM)
write eeprom 0x80 "Hello World!"
```

Any thoughts?

**Comment by dl8dtl** [comment]
I'll try it on MacOS now.

**Comment by dl8dtl** [comment]
Hmm, my Mac ports' `makeinfo` is version 4.8, from 2004 (!). :-/
My FreeBSD's `makeinfo` is version 6.8, from 2021.

I guess that explains it …
