### ISSUE TITLE
Build dependencies for Fedora

### ISSUE THREAD

**Issue by merlinblack** [avrdudes/avrdude#891]
Here's a one-liner to install everything needed to compile on Fedora. Perhaps someone with wiki rights might like to add it next to the Debian flavor?
`sudo dnf install gcc-c++ git cmake flex bison elfutils-libelf-devel libusb-devel hidapi-devel libftdi-devel readline-devel`

**Comment by mariusgreuel** [comment]
@merlinblack I added the code to the wiki. Thanks for your help!
