### ISSUE TITLE
probably lgt8fx328p

### ISSUE THREAD

**Issue by HansaG** [avrdudes/avrdude#916]
hi there,
version 6.4 gives me a message saying "Device signature = 0x1e950f (probably lgt8fx328p)"
however version 6.3 does not.
![image](https://user-images.githubusercontent.com/102892004/161412899-c478f98e-bcb4-4a07-bd74-9066ca6c12e5.png)

**Comment by dl8dtl** [comment]
Both have the same signature code, and all versions up to 6.x picked the first matching one from the list.
The algorithm has changed in the upcoming v7.0 to prefer the one that has been specified on the commandline.
