### ISSUE TITLE
[bug #19679] debugwire programming does not reset the target

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#94]
Mikhail <favrdude@theamk.com>
Tue 24 Apr 2007 06:13:40 AM UTC

it seems that programming via debugWire does not reset the target. This leads to random actions soon after upload.
All other programming options reset target, so it feels really strange that debugWire does not.

This issue was migrated from https://savannah.nongnu.org/bugs/?19679

**Comment by mcuee** [comment]
This is really very old (2007). Just wondering if this is still relevant or not.
